### ISSUE TITLE
Error whilst trying to run docker compose up 

### ISSUE THREAD

**Issue by Edgehere** [rtzll/flask-todolist#16]
When I try to do the following commands I get an error. I am trying to run a `docker-compose` to run the `flask-todolist`. I have **Windows 10 version :  10.0.19043 N/A Build 19043** and **docker version  20.10.16, build aa7e414**. I am unable to run `docker-compose up `

commands on cmd 
```
docker-compose build
docker-compose up
```
Error:
```
C:\Users\Edge\Desktop\todolist\flask-todolist>docker-compose up
[+] Running 1/0
 - Container todolist  Created                                                                                     0.0s
Attaching to todolist
todolist  |  * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
todolist  | Usage: flask db upgrade [OPTIONS] [REVISION]
todolist  | Try 'flask db upgrade --help' for help.
todolist  |
todolist  | Error: While importing 'todolist', an ImportError was raised:
todolist  |
todolist  | Traceback (most recent call last):
todolist  |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 256, in locate_app
todolist  |     __import__(module_name)
todolist  |   File "/code/todolist.py", line 1, in <module>
todolist  |     from app import create_app
todolist  |   File "/code/app/__init__.py", line 2, in <module>
todolist  |     from flask_login import LoginManager
todolist  |   File "/usr/local/lib/python3.10/site-packages/flask_login/__init__.py", line 16, in <module>
todolist  |     from .login_manager import LoginManager
todolist  |   File "/usr/local/lib/python3.10/site-packages/flask_login/login_manager.py", line 24, in <module>
todolist  |     from .utils import (login_url as make_login_url, _create_identifier,
todolist  |   File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 13, in <module>
todolist  |     from werkzeug.security import safe_str_cmp
todolist  | ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.10/site-packages/werkzeug/security.py)
todolist  |
todolist exited with code 2
```

**Comment by rtzll** [comment]
Found this on [stackoverflow](https://stackoverflow.com/a/71653849). Seems that werkzeug removed the required method.
I've updated all dependencies and it built for me. Will push the fix in a second.
